"""
    DataMeta

    DataMeta  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import datameta_client_lib
from datameta_client_lib.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_api_keys(self):
        """Test case for get_user_api_keys

        All API keys for a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
