"""
    DataMeta

    DataMeta  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import datameta_client_lib
from datameta_client_lib.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_api_key(self):
        """Test case for create_api_key

        Create new API Key/Token  # noqa: E501
        """
        pass

    def test_delete_api_key(self):
        """Test case for delete_api_key

        Delete ApiKey by label  # noqa: E501
        """
        pass

    def test_register_user(self):
        """Test case for register_user

        Register a New User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
