"""
    DataMeta

    DataMeta  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import datameta_client_lib
from datameta_client_lib.model.reg_request import RegRequest


class TestRegRequest(unittest.TestCase):
    """RegRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegRequest(self):
        """Test RegRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
